services:
  nginx:
    container_name: startup-page
    image: nginx:latest
    restart: always
    ports:
      - 8082:80  # Map port 8081 on host to port 80 on container
    volumes:
      - ./html:/usr/share/nginx/html  # Mount your website files here
    networks:
      - default

networks:
  default:
    driver: bridge
