services:
  twingate_connector:
    container_name: twingate_connector
    image: twingate/connector:latest
    restart: always
    network_mode: host
    environment:
      - TWINGATE_NETWORK=${TWINGATE_NETWORK}
      - TWINGATE_ACCESS_TOKEN=${TWINGATE_ACCESS_TOKEN}
      - TWINGATE_REFRESH_TOKEN=${TWINGATE_REFRESH_TOKEN}
      - TWINGATE_LOG_ANALYTICS=${TWINGATE_LOG_ANALYTICS}
      - TWINGATE_LOG_LEVEL=${TWINGATE_LOG_LEVEL}

